### DISCUSSION TITLE
Azure pipeline to build maui with .net 8 rc2 ? What host agent ?

### DISCUSSION THREAD

**Discussion by gabsamples6** [dotnet/maui#17979] [General]
Hi ,
just wondering what changes I need to make or what VMImage I must use to build a maui app .net 8 in Azure pipelines?

Any gotchas?  Does anyone know?

many thanks

**Comment by JohnHDev** [comment]
We are building with macOS-12, haven't tried 13 yet.

**Comment by gabsamples6** [comment]
Hi @JohnHDev  
one of the initial tasks in my pipeline is to set the .net version - What value do you set here for .net 8?  thanks again 

    - task: UseDotNet@2
      displayName: .NET Version
      inputs:
        packageType: 'sdk'
        version: '7.0.100'

**Reply by JoacimWall** [reply]
- task: UseDotNet@2
        displayName: 'Use .Net 8'
        inputs:
         version: 8.0.x
         includePreviewVersions:  - task: CmdLine@2

        - task: CmdLine@2
        displayName: 'Install Maui workload --include-previews'
        inputs:
          script: 'dotnet workload install maui --include-previews'

      - task: CmdLine@2
        displayName: 'Install Ios Android workload ios --include-previews'
        inputs:
          script: 'dotnet workload install maui-android maui-ios --include-previews'

**Comment by gabsamples6** [comment]
@JoacimWall thanks for your reply,

Obviosly I can successfully build an android and iOS app in azure devops using .net 7 but in .net 8 the following is failing...

Do you or anyone have a sample pipeline i can use for .net 8 for both android and iOS?

I am getting
 _No matching sdk version could be found for specified version: 8.0.x Kindly note the preview versions are only considered in latest version searches if Include Preview Versions checkbox is checked.
[error]sdk version matching: 8.0.x could not be found_

```
**Its a very stripped down version of what we do and we have a template and with a bunch of parameters..** 
jobs:
  - job: 'Build Dev'
    displayName: 'Build Maui Android'
    timeoutInMinutes: 120
    pool:
      vmImage: 'windows-2022'
      demands:
      - MSBuild

    steps:


    - task: UseDotNet@2
      displayName: .NET Version
      inputs:
        packageType: 'sdk'
        version: '8.0.x' 
    
    - task: Bash@3
      displayName: Install MAUI
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear 
          dotnet workload install maui maui-android maui-ios --include-previews
          dotnet workload install android ios --include-previews
    
    - task: Bash@3
      displayName: Restore nuget
      inputs:
        targetType: 'inline'
        script: |
          cd ${{ parameters.clientPath}}/
          dotnet restore ${{parameters.clientName}}.MyApp.sln
        
       
     # Bump Android Version
    - task: android-manifest-version@1
      displayName: 'Bump Android Version to ${{ parameters.majorMinorVersionName }}.$(Build.BuildId)'
      inputs:
        sourcePath: ${{ parameters.androidManifestPath }}
        versionCodeOption: 'buildid'
        versionCode: $(Build.BuildId)
        versionCodeOffset:  ${{ parameters.versionCodeOffset }}
        versionName: '${{ parameters.majorMinorVersionName }}.$(Build.BuildId)'
        printFile: true
  

    - task: DownloadSecureFile@1
      name: androidKeyStore
      displayName: 'Download keystore from secure files:  ${{parameters.keystoreFilename}}'
      inputs:
        secureFile: ${{parameters.keystoreFilename}}

    - task: Bash@3
      displayName: Build Android App
      inputs:
        targetType: 'inline'
        script: |
          cd ${{ parameters.clientPath}}
          dotnet build src/${{parameters.clientName}}.MyApp/${{parameters.clientName}}.MyApp.csproj  -f net8.0-android -c Release -p:AndroidPackageFormat=aab -p:AndroidKeyStore=True -p:AndroidUseSharedRuntime="False" -p:AndroidSigningKeyStore="$(androidKeyStore.secureFilePath)" -p:AndroidSigningKeyPass="${{ parameters.keystorePassword }}" -p:AndroidSigningKeyAlias="${{ parameters.keyAlias}} " -p:AndroidSigningStorePass="${{ parameters.keyPassword }}"
     
    # Copy files to artifact directory  
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.artifactstagingdirectory)'
      inputs:        
        Contents: |
          **/*.aab
          **/*.apk
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true


     # Publish artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish release'
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'drop'
       publishLocation: 'Container'  
    - task: PowerShell@2
      displayName: App version 
      inputs:
            targetType: 'inline'
            script: |        
              Write-Host "Android Version ${{ parameters.majorMinorVersionName }}.$(Build.BuildId)"




```
