### DISCUSSION TITLE
Caching workloads in GH Actions

### DISCUSSION THREAD

**Discussion by tschbc** [dotnet/maui#20601] [Q&A]
How do I effectively cache workloads and packages in a GH Action?

This is what I'm currently using to cache (based on [Cache examples](https://github.com/actions/cache/blob/main/examples.md#c---nuget)):

```yaml
- name: Cache .NET dependencies
  uses: actions/cache@v4
  if: always()
  with:
    path: ~/.nuget/packages
    key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
    restore-keys: |
      ${{ runner.os }}-nuget-

- name: Install .NET MAUI ${{ env.MAUI_VERSION }} workload
  working-directory: ${{ env.BASE_PROJPATH }}
  run: |
    dotnet --version
    dotnet workload install maui ios maccatalyst --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/${{ env.MAUI_VERSION }}.json
```

I get a successful cache hit on subsequent runs, but dotnet goes and redownloads workloads all over again... so workloads must be stored outside `~/.nuget/packages`. But I don't know where, and I don't know where to look. Should I use `workload restore` instead? I'm running this on the `windows-2022` runner.

I'm also realizing that hashing csproj files as the key is a bad idea, since any change at all would change the key. I guess I could read the packages and versions from XML and hash them alone?
