### DISCUSSION TITLE
dotnet publish for MacCatalyst works locally but not in Github action (missing profile)

### DISCUSSION THREAD

**Discussion by MSicc** [dotnet/maui#21398] [Q&A]
I am not sure if here is the right place, but maybe someone is around to help.

I can use the dotnet publish command locally with my MacCatalyst app to produce a signed .pgk. This .pkg is accepted by Testflight without any problems.

After the initial, manual release, I wanted to set up a Github Action to build and upload to Testflight once I merge into my main branch.

I use the established action https://github.com/marketplace/actions/download-apple-provisioning-profiles to download the provisioning profiles, and they get stored in the worker's MobileProvision folder, according to the action output:

```
Run Apple-Actions/download-provisioning-profiles@v1
  with:
    bundle-id: com.msiccdev.timetraversehub
    issuer-id: ***
    api-key-id: ***
    api-private-key: ***
  env:
    DOTNET_ROOT: /Users/runner/.dotnet
Wrote MAC_APP_STORE profile 'TimeTraverseHub_Distribution' to '/Users/runner/Library/MobileDevice/Provisioning Profiles/c5e976d8-b3ca-4d09-b5c4-e50dd792b52a.mobileprovision'.
Wrote MAC_CATALYST_APP_DEVELOPMENT profile 'TimeTraverseHub_Dev_Profile' to '/Users/runner/Library/MobileDevice/Provisioning Profiles/cdf03a76-5084-4cbc-88f9-a8e9e77e5ee3.mobileprovision'.
```

The  dotnet publish command however always says there is no matching profile...

```
MSBuild version 17.9.6+a4ecab324 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/Users/runner/.dotnet/packs/Microsoft.MacCatalyst.Sdk/17.2.8043/tools/msbuild/iOS/Xamarin.Shared.targets(1805,3): error : The specified MacCatalyst provisioning profile 'TimeTraverseHub_Distribution' could not be found [/Users/runner/work/TimeTraverseHub/TimeTraverseHub/src/TimeTraverseHub/TimeTraverseHub.csproj::TargetFramework=net8.0-maccatalyst]
/Users/runner/.dotnet/packs/Microsoft.MacCatalyst.Sdk/17.2.8043/tools/msbuild/iOS/Xamarin.Shared.targets(1805,3): error :          [/Users/runner/work/TimeTraverseHub/TimeTraverseHub/src/TimeTraverseHub/TimeTraverseHub.csproj::TargetFramework=net8.0-maccatalyst]
```

The same command (copy and pasted) works on my local machine, though.

Here is the code for both action steps as well:

```
    - name: Download Apple Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
         bundle-id: 'com.msiccdev.timetraversehub'
         issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
         api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
         api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
       
    - name: dotnet publish
      run: dotnet publish -f net8.0-maccatalyst -c Release /p:MtouchLink=SdkOnly /p:CreatePackage=true /p:EnableCodeSigning=true /p:EnablePackageSigning=true /p:CodeSignKey=${{env.CODESIGNKEY}} /p:CodesignProvision=${{env.CODESIGNPROVISION}} /p:CodesignEntitlements=${{env.CODESIGNENTITLEMENTS}} /p:PackageSigningKey=${{env.PACKAGESIGNKEY}} -o ./publish
      working-directory: ./src/TimeTraverseHub/
```

Thanks in advance for any tip/help with that.
