### DISCUSSION TITLE
Working example for a `dependabot` script for `MAUI` apps

### DISCUSSION THREAD

**Discussion by AndreasReitberger** [dotnet/maui#24664] [Q&A]
I tried to setup a working script to update nugets for a `.NET MAUI` application. However either the dependabot does not find any updates or any error occurs that the workloads are missing. Does anybody have a working script for sharing? 

```yaml
version: 2
#registries:
#  custom-nuget:
#    type: nuget-feed
#    url: https://api.nuget.org/v3/index.json
updates:
- package-ecosystem: nuget
  directory: "/src/"
#  registries:
#    - custom-nuget
  schedule:
    interval: daily
    # Run at 10pm Pacific time
    time: "22:00"
    timezone: "America/Los_Angeles"
  open-pull-requests-limit: 25
  labels:
      - "nuget"
      - "dependencies"
```

This script gives me an error that the `workload` is missing.
