### DISCUSSION TITLE
How to pin workload/ .net maui versions

### DISCUSSION THREAD

**Discussion by IeuanWalker** [dotnet/maui#29200] [Q&A]
### Description

In our Azure pipelines we do the following - 
```yaml
    - script: |
        echo Mac OS version:
        sw_vers -productVersion
        echo
        echo Installed Xcode versions:
        ls /Applications | grep 'Xcode'
        echo
        echo currently selected xcode:
        xcrun xcode-select --print-path
        echo
        echo selecting latest xcode...
        sudo xcode-select -s /Applications/Xcode_16.2.app
        sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
        xcrun xcode-select --print-path
        xcodebuild -version
      displayName: Select Xcode Version

    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        packageType: 'sdk'
        version: '9.0.102'

    - task: CmdLine@2
      displayName: Install .NET MAUI Workload
      inputs:
        script: |
          dotnet nuget locals all --clear
          dotnet workload install maui --version 9.0.102.1
          dotnet --version
```

And everything is working as expected. Locally though I'm getting some errors when trying to debug the iOS app, xcode version issues and a linking issue.

I've tried creating a global.json file, but then the connection to the mac constantly fails -
![Image](https://github.com/user-attachments/assets/dc110e34-9977-4956-a710-902236ec2844)

Without the `workloadVersion` added to the global.json I'm able to connect to the mac, but get the same errors - 
![Image](https://github.com/user-attachments/assets/df00d14e-1179-4ec5-ad21-4847ffa1db55)

### Version with bug

9.0.30 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Relevant log output

```shell

```
