### DISCUSSION TITLE
Build MAUI app using GitHub actions

### DISCUSSION THREAD

**Discussion by maxkoshevoi** [dotnet/maui#2945] [Q&A] [answered]
I'm trying to build my maui app, but action fails when installing workload: https://github.com/maxkoshevoi/NureTimetable/runs/3894450932?check_suite_focus=true

Is there something I'm missing?

**Comment by Psypher9** [comment]
Have you tried building on a Windows machine? Just to see if the workload is able to install.

**Reply by maxkoshevoi** [reply]
Workload installs on my Windows machine without any issues, and project starts building. But project itself still has some issues, so build fails, but that's on me to figure out.

![image](https://user-images.githubusercontent.com/6609929/137949688-cfb2f089-3685-45b6-aa2a-0a227312ee0c.png)

**Reply by charleszh-dev** [reply]
Hi, here are some repos that may help you.
- [WeatherTwentyOne](https://github.com/davidortinau/WeatherTwentyOne/blob/main/.github/workflows/dev.yml)
- [Booster](https://github.com/realZhangChi/Booster/blob/main/.github/workflows/build-and-unit-test.yml)

**Comment by maxkoshevoi** [comment, marked as answer]
Issue was that I was using linux agent 🤦‍♂️

Following action does the trick:
```yml
name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
    name: Build ${{ matrix.configuration }}
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Install workload
      run: dotnet workload install maui-android
    - name: Setup Java SDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build
      run: dotnet build -c ${{ matrix.configuration }}
```
