### DISCUSSION TITLE
iOS signing on Azure Devops pipeline

### DISCUSSION THREAD

**Discussion by vfongmala-willowinc** [dotnet/maui#4036] [Q&A]
How can I do the iOS signing on Azure Devops pipeline?
I tried to put this into my `.csproj` but it doesn't work.
```
<CodesignKey>Apple Development: YOUR NAME</CodesignKey>
<CodesignProvision>VS: com.COMPANY.APPID Development</CodesignProvision>
```

error message was 
```
Could not find any available provisioning profiles for <PROJECT_NAME> on iOS
```

**Comment by owaits** [comment]
Have you tried installing the provisioning profile on the build agent? I think you will need to have the following in your yaml.

```
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'ios_distribution.p12'
    certPwd: '$(P12password)'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'iOS_Distribution.mobileprovision'
```

I will be trying this out tomorrow so will let you know how it goes.
