### ISSUE TITLE
Set up an Azure Devops image with maui pre-installed, as this would reduce CI times for most users significantly

### ISSUE THREAD

**Issue by frackham** [dotnet/maui#16052]
### Description

Azure devops pipelines setup guidance usually recommends `windows-latest` or `windows-2022`. This still needs something like the following step to be run as this image (windows-2022 is latest at time of writing) doesn't include the MAUI VS workload:

```cli
dotnet workload install maui
```

By providing an agent definition with Visual Studio + MAUI workloads preset up, this costly step would be reduced. For me, this is between 5 and 9 minutes, Azure Devops dependent. Consider this multiplied out by the number of users using a very standard use case (Azure Devops build and release)!

### Public API Changes

None, other than docs changes. This would only require this team liaising with the Azure Devops/Azure team (not sure how your internal teams set up ownership of images).

Note that self-hosted agents aren't the approach here - you *should* be wanting to reduce your compute time for the masses of users (from both a UX perspective, and a compute/energy efficiency perspective!) who won't mess with self hosted agents, and pushing people towards managing agents is going to cut out a lot of devs who don't have infrastructure support.

### Intended Use-Case

In Azure Devops yaml definitions for a pipeline, e.g.:

```yaml

trigger:
- main

pool:
  vmImage: windows-2022

```

...becomes...

```yaml

trigger:
- main

pool:
  vmImage: windows-2022-maui # Or whatever name seems appropriate.
```
