### ISSUE TITLE
dotnet publish for iOS fails on Azure but succeeds locally on the same build machine

### ISSUE THREAD

**Issue by ValonK** [dotnet/maui#17029]
### Description

When attempting to publish my iOS app via Azure, I encounter an error related to the iOS code signing key. The same dotnet publish command works as expected when run locally on the build machine outside of Azure. The specific error message received is:

`iOS code signing key 'iPhone Distribution: ******' not found in keychain.`

Workarounds Attempted:

1. Checked the entire build pipeline for any misconfigurations or references to the incorrect key.
2. Ensured that the correct certificate is present in the keychain on the build machine.
3. Cleaned and rebuilt the project.

This is my pipeline:

```
  - task: UseDotNet@2
    displayName: 'Install .NET Sdk'
    inputs:
      packageType: sdk
      version: 8.0.x
      includePreviewVersions: true
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: CmdLine@2
    displayName: 'Install Maui Workload'
    inputs:
      script: 'dotnet workload install maui-android maui-ios --source https://api.nuget.org/v3/index.json --include-previews true'

  - task: DownloadSecureFile@1
    name: certificate
    inputs:
      secureFile: 'Certificate.p12'

  - task: CmdLine@2
    displayName: Create Keychain
    inputs:
      script: |
        security create-keychain -p "****" "buildKeychain"
        
        security list-keychains -d user -s "buildKeychain" $(security list-keychains -d user | tr -d '"')
        
        security set-keychain-settings "buildKeychain"
        
        security import $(certificate.secureFilePath) -k "buildKeychain" -P "" -T "/usr/bin/codesign"
              
        security set-key-partition-list -S apple-tool:,apple: -s -k "****" -D "iPhone Distribution: ****" -t private buildKeychain
        
        security default-keychain -d user -s buildKeychain
        
        security unlock-keychain -p "****" buildKeychain
        
        security find-identity -v -p codesigning

  - task: DotNetCoreCLI@2
    displayName: 'Build / Archive'
    inputs:
      command: 'publish'
      publishWebProjects: false
      arguments: '$(Build.SourcesDirectory)/src/Project.csproj -f net8.0-ios -c Release -p:CodesignKeychain=buildKeychain -p:RuntimeIdentifier=ios-arm64 -p:ArchiveOnBuild=true -p:IsPublishing=true -p:ApplicationVersion=$(Build.BuildId) -p:ApplicationDisplayVersion=1.4.$(Build.BuildId) -o $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: CmdLine@2
    displayName: Delete Keychain
    inputs:
      script: 'security delete-keychain buildKeychain'
```

Executing this command on the Build machine without Azure works as expected:

`dotnet publish -f net8.0-ios -c Release -p:CodesignKeychain=buildKeychain -p:RuntimeIdentifier=ios-arm64 -p:ArchiveOnBuild=true -p:IsPublishing=true`

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

no

### Relevant log output

```shell
/Users/user/Desktop/dev/agent/_work/_tool/dotnet/sdk/8.0.100-preview.7.23376.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/user/Desktop/dev/agent/_work/1/s/Project.csproj::TargetFramework=net8.0-ios]
/Users/user/Desktop/dev/agent/_work/_tool/dotnet/packs/Microsoft.iOS.Sdk/16.4.8694-net8-p7/tools/msbuild/iOS/Xamarin.Shared.targets(1795,3): error : iOS code signing key ''iPhone Distribution: ****'' not found in keychain. /Users/user/Desktop/dev/agent/_work/1/s/Project.csproj::TargetFramework=net8.0-ios]
/Users/user/Desktop/dev/agent/_work/_tool/dotnet/packs/Microsoft.iOS.Sdk/16.4.8694-net8-p7/tools/msbuild/iOS/Xamarin.Shared.targets(1795,3): error :          [/Users/user/Desktop/dev/agent/_work/1/s/Project.csproj::TargetFramework=net8.0-ios]
##[error]Error: The process '/Users/user/Desktop/dev/agent/_work/_tool/dotnet/dotnet' failed with exit code 1
```
