### ISSUE TITLE
iOS Application crashes on startup when built through Azure pipeline

### ISSUE THREAD

**Issue by gsk143** [dotnet/maui#18652]
### Description

iOS Application crashes on startup when built through Azure pipeline

Relevant code

```xml
<TargetFrameworks>net7.0-android;net7.0-ios</TargetFrameworks>
<MauiVersion>7.0.81</MauiVersion>
```

```xml
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<!-- Only needed when you have a need for entitlements -->
		<!-- <CodesignEntitlement>Entitlements.plist</CodesignEntitlement> -->
		<CodesignKey>(my key)</CodesignKey>
		<CodesignProvision>(my provision)</CodesignProvision>
		<MtouchLink>SdkOnly</MtouchLink>
		<MtouchExtraArgs>$(MtouchExtraArgs) --weak-framework=NewsstandKit</MtouchExtraArgs>
</PropertyGroup>
```

command on azure 

```yml
pool: macOS 13
steps:
- task: DotNetCoreCLI@2
  displayName: 'Build MAUI IOS Project'
  inputs:
    command: publish
    publishWebProjects: false
    projects: path to .csproj
    arguments: '-f:net7.0-ios -c:Release -p:TcpPort=58181 -p:ArchiveOnBuild=true -p:EnableAssemblyILStripping=false'
    zipAfterPublish: false
    modifyOutputPath: false
```

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

**Comment by gsk143** [comment]
hi @jfversluis I can provide the iOS crash log maybe that could help
[2023-11-09_12-03-19.8980_+0530-f79a5dba0a86f81405ec356c13c7abd7fc767cdf.txt](https://github.com/dotnet/maui/files/13308402/2023-11-09_12-03-19.8980_%2B0530-f79a5dba0a86f81405ec356c13c7abd7fc767cdf.txt)

When I try building from my local machine it works fine but after running the command I use xcode and use archive to push it to the internal track (not sure if that changes things) 

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui-ios                   7.0.86/7.0.100        SDK 7.0.300
maui-android               7.0.86/7.0.100        SDK 7.0.300

I have xcode 14.3.1

**Comment by omarraja786** [comment]
I had this issue too @gsk143 . Ran fine locally with net 7 but iOS crashed when deployed.

Solved this by keeping solution in dotnet 7 but upgrading pipelines to dotnet 8 and ensured the following parameters were set (Of course put each task i've put here in the correct area):

```
pool:
  vmImage: 'macos-13'
```
```

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    includePreviewVersions: true

```

```
- script: |
    sudo xcode-select -s /Applications/Xcode_15.0.app
  displayName: Selects a specific version of Xcode
```


This task can probably be changed a bit to your liking but ensure its using net 8.0-ios
```
- task: DotNetCoreCLI@2
  displayName: 'MAUI Build and Publish iOS'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)/Project/Project.csproj'
    arguments: '-f net8.0-ios -c $(BuildConfiguration) -p:TargetFrameworks=net8.0-ios -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="$(APPLE_CERTIFICATE_SIGNING_IDENTITY)" -p:CodesignProvision="$(APPLE_PROV_PROFILE_UUID)"'
    zipAfterPublish: false
  env:
    DISABLE_BITCODE: 'yes'
```

**Comment by PureWeen** [comment]
@rolfbjarne  thoughts?

**Comment by rolfbjarne** [comment]
Unfortunately the crash report isn't overly helpful, but in any case the first step in these cases is often to try to replicate the problem locally - so does this happen if you build the Release configuration with EnableAssemblyILStripping=false locally?

**Comment by gsk143** [comment]
@omarraja786 Hai I tried your method but it gives the error 
wwwroot/css/app.css' would result in a file outside of the app bundle and cannot be used.

@rolfbjarne Yeah log isn't exactly helpful so even I am stumped on what is the issue exactly tbh. But I tried building it locally and yes I was able to reproduce it with EnableAssemblyILStripping=false. 

So before we started working on CI process and clean up we used to release by a slightly different method(Not sure why like this, I joined in the middle of the project)

```csproj
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
	         <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
	         <CodesignKey>(Development Key)</CodesignKey>
                 <CodesignProvision>(provison)</CodesignProvision>
		 <MtouchLink>SdkOnly</MtouchLink>
		 <MtouchExtraArgs>$(MtouchExtraArgs) --weak-framework=NewsstandKit</MtouchExtraArgs>
        </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0-ios|AnyCPU'">
	        <CreatePackage>false</CreatePackage>
	        <CodesignProvision>Automatic</CodesignProvision>
	        <MtouchLink>SdkOnly</MtouchLink>
	        <MtouchExtraArgs>$(MtouchExtraArgs) --weak-framework=NewsstandKit</MtouchExtraArgs>
        </PropertyGroup>
```
I rebuild the project and run the below commmand
```dotnet publish -f:net7.0-ios -c:Debug /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory=/Users/<USER>/Library/Caches/Xamarin/XMA/SDKs/dotnet/ /p:EnableAssemblyILStripping=false```

After I use xcode->organizer->upload and I select the distribution cert and profile
Above method is working just fine. Idk if this helps or changes anything as the only thing changing is cert on publish command

**Comment by rolfbjarne** [comment]
If you get a binlog from both the working and the failing build (see https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs), we could compare and see where the difference is.

**Comment by ahoffmandevelopment** [comment]
I don't know if it'll help anybody else, but I was having the same problem and it ended up being a problem with a library that I had recently brought in, TinyMapper. After removing the library, my release builds now run correctly.

**Comment by vikher** [comment]
Experiencing a similar issue here! Building the app locally seems to function without a hitch, but encountering trouble when attempting to install it via the pipeline. Getting an 'unable to install' error, This app cannot be installed because its integrity could not be verified. Any insights or suggestions on resolving this would be greatly appreciated!
Here's the YAML file content

```
trigger:
  branches:
    include:
      - develop

variables:
    BuildConfiguration: Release
    DotNetVersion: 7.x
    iOSVersion: net7.0-ios

pool:
  vmImage: macos-latest
  demands: xcode

steps:
- task: InstallAppleCertificate@2
  displayName: 'Install Apple P12 Cert'
  inputs:
    certSecureFile: 'apple_prod_signing_cert_20230316.p12'
    certPwd: '$(AppleCertificatePassword)'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Apple Provisioning Profile'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'Ad_Hoc_comcinemarkcinemarkapp.mobileprovision'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(DotNetVersion)'

- task: CmdLine@2
  displayName: 'Install Maui Workload'
  inputs:
    script: 'dotnet workload install maui'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish $(BuildConfiguration)'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-f:$(iOSVersion) -c:$(BuildConfiguration) -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey=$(CodesignKey) -p:CodesignProvision=$(CodesignProvision)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: CopyFiles@2
  displayName: 'Copy file from Build to Staging'
  inputs:
    SourceFolder: '$(Agent.BuildDirectory)'
    Contents: '**/*.ipa'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish the Staging Files.'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop_maui_ios'
    publishLocation: 'Container'
```
