### ISSUE TITLE
GitHub Actions no longer builds MAUI (Android): Java SDK 11.0 or above is required when using .NET 6 or higher

### ISSUE THREAD

**Issue by iamalexmang** [dotnet/maui#18906]
### Description

Starting today the Android builds fail on GitHub Actions using GitHub's runners.

Specifically, a build that ran fine 6h ago, now fails with "Java SDK 11.0 or above is required when using .NET 6 or higher"

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

7.0.100

### Affected platforms

Android

### Relevant log output

```shell
Error: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\targets\Microsoft.Android.Sdk.Tooling.targets(20,5): error XA0031: Java SDK 11.0 or above is required when using .NET 6 or higher. Download the latest JDK at: https://aka.ms/msopenjdk [D:\a\MAE-Alerte\MAE-Alerte\src\Alerte\Mobile\Mobile\Mobile.csproj::TargetFramework=net7.0-android]
```

**Comment by ErisApps** [comment]
Hii, I saw a related issue on the runner-images github repo, which should contain a workaround for this issue that you described. It can be found here: https://github.com/actions/runner-images/issues/8837

**Comment by jfversluis** [comment]
I've seen this mentioned a couple of times now. I think what happens is that the images are being updated to use .NET 8 while your project is still on .NET < (less than) 8. Somehow this error is triggered.

A couple of possible solutions here:
* Use a `global.json` that pins your project to .NET 7
* Use the `actions/setup-dotnet` step to select .NET 7 and do your build after that. You might need to install the .NET MAUI workload after doing this to make sure it's available
* Update your project to .NET 8
* There is also a task to select the Java version, but seeing that it has worked before it seems weird that you'd have to do this, although it probably works.

As far as I know there is not much we can do about this on our end, this is just the pain with hosted build agents and a period where multiple things update I guess.

If someone could confirm that one of these solutions work and which one, that would be great!

**Comment by cdefgah** [comment]
I get this issue in Azure Pipelines, the error was the same. Fixed it adding this code to pipelines.yml file:

```yaml
      - task: JavaToolInstaller@0
        displayName: "Install Java Support"
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
```

Probably there's a similar workaround for GH Actions.

**Comment by iamalexmang** [comment]
@jfversluis the action which started failing I:
1. Run setup-dotnet, specifying the .NET version, like this:
    ```
    - name: Setup .NET SDK ${{ env.DOTNETVERSION }}
      uses: actions/setup-dotnet@v2
        with:  
          dotnet-version: '${{ env.DOTNETVERSION }}'
    ```
2. Second, I also Install .NET Maui already:
    ```
    - name: Install .NET MAUI
      shell: bash
      run: |
        dotnet nuget locals all --clear 
        dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
        dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
    ```

This effectively rules out the second bullet point.
I agree that setting up Java should not be the case..., but neither should be upgrading to .NET 8, IMHO.
