### ISSUE TITLE
Stop silent iOS updates with hard minimum requirements on xcode

### ISSUE THREAD

**Issue by svaldetero** [dotnet/maui#19934]
### Description

I have a maui ios app the builds in Azure Devops Pipelines. It builds fine on monday. On Tuesday it now has a build error. The reason is that Microsoft.NET.Sdk.iOS.Manifest-8.0.100 nuget / workload was updated from 17.0 to 17.2. Which now has a hard requirement on XCode 15.1. I previously pinned the Xcode version to 15.0.1 since that's what was required before and xcode 15 is not the default version on macos-13 image.

This scenario has happened several times before with .net7.

Does every minor update imply a new xcode requirement? I'm even pinning .net to 8.0.x, but that didn't help since it is still 8.0.100 but the workload went from 17.0 -> 17.2.

For reference, here are my steps to setup the build:

```
parameters:
  platform: 'any'
  workload: 'maui-ios maui-android'
  xcodeversion: '15.0.1'

steps:
- task: UseDotNet@2
  displayName: 'Setup .NET' 
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet workload install ${{ parameters.workload }} --source https://api.nuget.org/v3/index.json
    dotnet workload list
  displayName: 'Install MAUI Workload(s)'

- bash: |

    echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_${{ parameters.xcodeversion }}.app
    sudo xcode-select --switch /Applications/Xcode_${{ parameters.xcodeversion }}.app/Contents/Developer
  
  displayName: 'Select Xcode version'

```

I comment out the xcode step when the default is the correct version, however this problem inevitable happens again at some point.

### Steps to Reproduce

1. Create a working build pipeline
2. Do nothing
3. Wait for a workload update that has a new minimum xcode requirement
4. Next time building the pipeline breaks

### Version with bug

8.0.5

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

8.0.3

### Affected platforms

iOS

### Did you find any workaround?

Update my pipeline to select a different xcode version OR update the workload install step to pin to a specific rollback file using an undocumented parameter.

### Relevant log output

```shell
These are the errors that I get when this scenario happens:

ILLINK : warning MT0079: The recommended Xcode version for Microsoft.iOS 17.2.8004 is Xcode 15.1 or later. The current Xcode version (found in /Applications/Xcode_15.0.1.app/Contents/Developer) is 15.0.1. [/Users/runner/work/1/s/Mobile/src/Maui/i2.POS.Maui.csproj::TargetFramework=net8.0-ios]
ILLink : unknown error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [/Users/runner/work/1/s/Mobile/src/Maui/i2.POS.Maui.csproj::TargetFramework=net8.0-ios]
ILLINK : error MT0180: This version of Microsoft.iOS requires the iOS 17.2 SDK (shipped with Xcode 15.1). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/1/s/Mobile/src/Maui/i2.POS.Maui.csproj::TargetFramework=net8.0-ios]
ILLINK : error MT2301: The linker step 'Setup' failed during processing: This version of Microsoft.iOS requires the iOS 17.2 SDK (shipped with Xcode 15.1). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/1/s/Mobile/src/Maui/i2.POS.Maui.csproj::TargetFramework=net8.0-ios]
```
