### ISSUE TITLE
CodesignEntitlements doesn't seem to work in project

### ISSUE THREAD

**Issue by thedee** [dotnet/maui#23045]
### Description

When trying to set the entitlements in the project the build pipeline doesn't seem to pick it up.  What happens is I get the error:
"This app cannot be installed because its integrity could not be verfied"

In my Maui project I have this:
```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
	<CodesignEntitlements>Platforms/iOS/Entitlements.prod.plist</CodesignEntitlements>
	<CodesignKey>iPhone Distribution: XXX (XXXXXXXX)</CodesignKey>
	<CodesignProvision>AdHoc Distribution</CodesignProvision>
	<UseInterpreter>true</UseInterpreter>
	<MtouchLink>SdkOnly</MtouchLink>
</PropertyGroup>
```

and in my pipeline I have this:
```
- task: CmdLine@2
    displayName: 'Build project'
    inputs:
      script: 'dotnet publish -f net8.0-ios -c Release'
```

The ipa gets created but I get the error I listed above.

If I change my pipleline to this it works and runs property on the device:
```
- task: CmdLine@2
    displayName: 'Build project'
    inputs:
      script: 'dotnet publish -f net8.0-ios -c Release -p:CodesignEntitlements=Platforms/iOS/Entitlements.prod.plist'
```

Why doesn't the build pickup the project properties at build time if they are not being passed as a param on the publish?

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS
