### ISSUE TITLE
Maui not building in Azure pipeline

### ISSUE THREAD

**Issue by ranjithtech** [dotnet/maui#23252]
### Description

We are building a MAUI app migrated from Xamarin. The application builds and runs smoothly on a local mac machine, but when I moved it to Azure pipeline to build, it is failing with below error.

`error CS0246: The type or namespace name 'MauiTextField' could not be found (are you missing a using directive or an assembly reference?) [/Users/runner/work/1/s/TestMobile/DashMobile.csproj::TargetFramework=net8.0-ios]
         /Users/runner/work/1/s/TestMobile/Controls/Handlers/DoneEntryHandler.iOS.cs(37,35): `

The maui handler code for the above error is as below.

```
using CoreGraphics;
using Microsoft.Maui.Handlers;
using Microsoft.Maui.Platform;
using UIKit;

namespace TestMobile.Controls.Handlers
{
    public class DoneEntryHandler : EntryHandler
    {
        protected override void ConnectHandler(MauiTextField platformView)
        {
            base.ConnectHandler(PlatformView);

            // handler code
        }
    }
}
```

### Steps to Reproduce

The Azure build task is

```
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: iOS/DashMobile.iOS.csproj
    arguments: '--framework net8.0-ios --configuration:Release --verbosity d'
```

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

.Net SDK Version: 8.0.302
