### ISSUE TITLE
maui workload 8.0.61/8.0.100 introduced NativeAOT runtime error in EFC .net 8

### ISSUE THREAD

**Issue by chrisweihu** [dotnet/maui#23595]
### Description

We use Azure DevOps Pipeline to build Maui .Net 8 iOS app. This runtime error is throw by EF.Sqlite .net 8 when calling DbContext.Migrate(). The error started to occur yesterday with no yaml change in our azure build pipeline. 
Here is the runtime error message: 

> Exception:Model building is not supported when publishing with NativeAOT. Use a compiled model.,
> InnerException:, StackTrace: at Microsoft.EntityFramework-Core.Internal.DbContextSer-vices.CreateModel(Boolean
> designTime)

I found this [answer](https://github.com/dotnet/efcore/issues/32496#issuecomment-1837210627) stating that the NativeAOT publishing is not yet supported on EFC .net 8.

We compared the Installed .NET SDK and MAUI workload version on Azure MAUI build Pipeline between Wednesday (No error) and Friday(Has NativeAOT error):
Both builds installed .NET SDK: 8.0.300
Wednesday (No error) - installed maui workload **8.0.40**/8.0.100
Friday(Has NativeAOT error) - installed maui workload **8.0.61**/8.0.100

It looks like  maui workload 8.0.61 has introduced the EF NativeAOT error. I have not found a working solution that allows us to install specified maui workload  version.

I have tried the following work-arounds, but no luck so far:
1. install maui workload with specific version using  '--from-rollback-file'
`dotnet workload install maui --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/8.0.1xx.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json --source https://api.nuget.org/v3/index.json`
This will fail with message: 
`Workload installation failed: Failed to install manifest microsoft.net.sdk.maui version 8.0.4: Version 8.0.4 of package microsoft.net.sdk.maui.manifest-8.0.100 is not found in NuGet feeds [https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json"..]`

 2. Add `<PublishAot>false</PublishAot> ` to Maui project to disable Publish AOT 

### Steps to Reproduce

Create a Maui iOS azure build pipeline using the following YAML configuration:
```
variables:
- name: BuildParameters.serverEndpoint
  value: [xxx]
- name: BuildParameters.configuration
  value: Release
- name: BuildConfiguration
  value: Release
- name: BuildPlatform
  value: iPhone
- name: iOScertPassword
  value: [xxx]
- name: system.debug
  value: false
name: $(date:yyyyMMdd)$(rev:.r)
stages:
- stage: __default
  jobs:
  - job: Phase_1
    displayName: Phase 1
    cancelTimeoutInMinutes: 1
    pool:
      name: Azure Pipelines
      vmImage: 'macos-14'
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          sudo xcode-select -s /Applications/Xcode_15.4.app
          xcrun xcode-select --print-path
          xcodebuild -version
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '6.9.1'

    - task: UseDotNet@2
      displayName: 'Install .NET sdk'
      inputs:
        packageType: sdk
        version: 8.0.300
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: InstallAppleCertificate@2
      displayName: Install an Apple certificate
      inputs:
        certSecureFile: '[xxx].p12'
        certPwd: [xxx]
        deleteCert: false
        deleteCustomKeychain: false
        setUpPartitionIdACLForPrivateKey: false
    - task: InstallAppleProvisioningProfile@1
      displayName: Install an Apple provisioning profile
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: '[xxx].mobileprovision'
    - task: NuGetCommand@2
      name: NuGetCommand2
      displayName: NuGet restore BGC.Cambio.Mobile.sln
      inputs:
        command: 'restore'
        restoreSolution: '[xxx]Mobile.sln'
        feedsToUse: 'select'
        includeNuGetOrg: true
        noCache: true
      enabled: False
    - task: Bash@3
      displayName: 'Install Maui Workload'
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear          
          dotnet workload install maui --source https://api.nuget.org/v3/index.json
          
    - task: CmdLine@2
      inputs:
        script: |
          echo dotnet --info:
          dotnet --info
          echo dotnet workload --info:
          dotnet workload --info
    - task: DotNetCoreCLI@2
      displayName: 'Build the iOS Binaries'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '[xxx].MAUI.csproj'
        arguments: '-f:net8.0-ios -c:Release /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false --source https://api.nuget.org/v3/index.json'
        zipAfterPublish: false
    - task: CopyFiles@2
      displayName: 'Copy file from Build to Staging'
      inputs:
        SourceFolder: '$(Agent.BuildDirectory)'
        Contents: '**/*.ipa'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
        OverWrite: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish the Staging Files.'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'


```

Create a MAUI project that use "Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.4". It should contains a code either call DbContext.Database.Migrate() or DbContext.Database.EnsureCreated().

Install the build onto a iOS device (don't use simulator)

App crashes when DbContext.Database.Migrate() or DbContext.Database.EnsureCreated() is called.

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Did you find any workaround?

NO
