### ISSUE TITLE
Publishing to BAR/Maestro will no longer support tokens

### ISSUE THREAD

**Issue by premun** [dotnet/maui#23974]
I noticed that you're still using `$(MaestroAccessToken)` when publishing internal builds in https://github.com/dotnet/maui/blob/4856f37f5b5f8e9701146f6b7b6fc27c336938a3/eng/pipelines/common/sdk-insertion.yml#L73.

This token is getting deprecated in favour of using a secretless auth via a service connection.
You will need to change how you do this or your internal builds will soon break.
The change is not complicated and goes as follows:

If your pipeline has something like this:
```yaml
- task: DotNetCoreCLI@2
  displayName: Generate and publish BAR manifest
  inputs:
    projects: $(Build.SourcesDirectory)\src\Workload\Microsoft.Maui.Sdk\Microsoft.Maui.Sdk.csproj
    arguments: >-
      -t:PushManifestToBuildAssetRegistry
      -p:BuildAssetRegistryToken=$(MaestroAccessToken)
      -p:OutputPath=$(Build.StagingDirectory)\nuget-signed\
      -v:n -bl:$(Build.StagingDirectory)\binlogs\push-bar-manifest.binlog
  condition: and(succeeded(), eq('${{ parameters.pushMauiPackagesToMaestro }}', 'true'))
```

it will need to change to something like this:

```yaml
- task: AzureCLI@2
  displayName: Generate and publish BAR manifest
  inputs:
    azureSubscription: "Darc: Maestro Production"
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      dotnet msbuild $(Build.SourcesDirectory)\src\Workload\Microsoft.Maui.Sdk\Microsoft.Maui.Sdk.csproj -t:PushManifestToBuildAssetRegistry -property:OutputPath=$(Build.StagingDirectory)\nuget-signed\
        -v:n -bl:$(Build.StagingDirectory)\binlogs\push-bar-manifest.binlog
    condition: and(succeeded(), eq('${{ parameters.pushMauiPackagesToMaestro }}', 'true'))
```

The differences between the snippets above are:
-	`AzureCLI@2` task is used
-	The `Darc: Maestro Production` service connection is used.
Your pipeline will need to be approved to use this connection (reach out to First Responders).
-	The `$(MaestroAccessToken)` secret is removed
