### ISSUE TITLE
iOS Release pipelines taking an hour

### ISSUE THREAD

**Issue by IeuanWalker** [dotnet/maui#25022]
### Description

iOS Azure CI pipeline taking an hour and causing it too fail - 
![image](https://github.com/user-attachments/assets/d4345772-c9cc-4cd3-8109-41433f1b07f4)

All the steps are completed but takes almost an hour to produce a build - 
![image](https://github.com/user-attachments/assets/ae2174a0-f0e1-42a1-b1c4-e96d9ff35573)

Majority of the time it's stuck on  -
`Optimizing assemblies for size. This process might take a while.`

Our XF iOS pipeline only takes 6m

### Steps to Reproduce

```yaml
trigger: none
variables:
- name: 'BUILD_CONFIGURATION'
  value: 'Release'
- name: 'DOTNET_VERSION'
  value: '8.0.x'
- name: 'FRAMEWORK_IOS'
  value: 'net8.0-ios'
- name: 'PROJECT_PATH'
  value: 'src/App/App.csproj'
- name: 'ARTIFACT_IOS_DROP_NAME'
  value: 'drop-ios'
- group: IosVariables

pool:
  vmImage: 'macos-14'
  demands: xcode

steps:
- script: |
    echo Mac OS version:
    sw_vers -productVersion
    echo
    echo Installed Xcode versions:
    ls /Applications | grep 'Xcode'
    echo
    echo currently selected xcode:
    xcrun xcode-select --print-path
    echo
    echo selecting latest xcode...
    sudo xcode-select -s /Applications/Xcode_16.0.app
    sudo xcode-select -switch /Applications/Xcode_16.app/Contents/Developer
    xcrun xcode-select --print-path
    xcodebuild -version
  displayName: Select Xcode Version
- task: UseDotNet@2
  displayName: .NET Version
  inputs:
    packageType: 'sdk'
    version: '$(DOTNET_VERSION)'
- task: CmdLine@2
  displayName: Install MAUI
  inputs:
    script: |
      dotnet nuget locals all --clear 
      dotnet workload install maui
- task: InstallAppleCertificate@2
  displayName: 'Get apple p12 certificate (Distribution)'
  inputs:
    certSecureFile: 'DistributionCertificate.p12'
    certPwd: '{PASSWORD}'
    deleteCert: true
- task: InstallAppleProvisioningProfile@1
  displayName: 'Get provisioning profile (CardiffGov-AdHoc for appcenter builds)'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'CardiffGovAdHoc.mobileprovision'
    removeProfile: true
- task: DotNetCoreCLI@2
  displayName: 'Build the iOS Binaries'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/App/App.csproj'
    arguments: '-f:net8.0-ios -c:Release /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false'
    zipAfterPublish: false
- task: CopyFiles@2
  displayName: Copy IPA to Artifact Staging Directory
  inputs:
    Contents: '**/*.ipa'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
- task: PublishBuildArtifacts@1
  displayName: Publish IPA
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(ARTIFACT_IOS_DROP_NAME)'
    publishLocation: 'Container'  
```

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by jfversluis** [comment]
I know the hosted build agents are a bit underpowered so it definitely might run for a while there, if you run it locally, how long does it run there? Do you know?

Not a great solution, but you can make the timeout longer with `timeoutInMinutes` on your task, or there might be a setting for your whole pipeline.

Looks like there is some additional info here too: https://github.com/actions/runner-images/issues/10200

@rolfbjarne is there anything people can do here to speed this up?

**Comment by IeuanWalker** [comment]
@jfversluis thanks, looks like i found that issue a few months back when I first started to look at the pipelines. Its increased by 12m since then - https://github.com/actions/runner-images/issues/10200#issuecomment-2223079762

Locally I think it only takes about 30m

**Comment by IeuanWalker** [comment]
@jfversluis I presume its this setting that's taking up all the time? 
![image](https://github.com/user-attachments/assets/887b840d-acaf-4553-93c1-6231379f6dff)

if it is, do you know if there is an argument I can add to the publish command to turn it off so a build can be tested quicker when needed?
```yaml
- task: DotNetCoreCLI@2
  displayName: 'Build the iOS Binaries'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/App/App.csproj'
    arguments: '-f:net8.0-ios -c:Release /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false'
    zipAfterPublish: false
```

**Comment by rolfbjarne** [comment]
You can disable llvm by passing `/p:MtouchUseLlvm=false` to `dotnet publish`, that should speed things up considerably.

**Comment by IeuanWalker** [comment]
thanks @rolfbjarne, that takes it down to about the same as the android pipeline -
![image](https://github.com/user-attachments/assets/254b942e-ee80-4e2c-a8be-4ed8a5a100e7)

**Comment by gabsamples6** [comment]
We are experienciing the same issue - no change in our pipeline 

**few months ago** 
![image](https://github.com/user-attachments/assets/71b7a72e-066e-4263-8c7a-253311b406ef)

**Now**
![image](https://github.com/user-attachments/assets/23caf828-e8de-4109-8a51-7bf138abfb69)

something has changed that increased this drammatically.

**Comment by rolfbjarne** [comment]
The best way to diagnose any differences would be if we could get an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) from an older (fast) build + newer (slow) build, that way we can compare the exact differences in the build (if any). The binlogs will also have timings, to see where the time is spend, which would be really useful in this scenario.

**Comment by gabsamples6** [comment]
@rolfbjarne  I have a feeling this is not a bug but a ADO agent issue , bcse depending on the time of the day I get different timings

our nightly build took  23 mins
![image](https://github.com/user-attachments/assets/7d460917-efa1-4652-92bf-86d9700606c1)

during the day it took 40-50 mins  and also I no longer have a way to get the "old" binlog etc 

but something is for sure  its consistently slower and takes longer, I know this does not help you as you need "facts" binlogs to compare..

**Comment by IeuanWalker** [comment]
@rolfbjarne sorry for late reply, was on holiday 👌

Here is the .binlog file from a CI that took about 1h10m
[msbuild.zip](https://github.com/user-attachments/files/17366870/msbuild.zip)

Tried looking at the logs myself using (https://msbuildlog.com) but couldn't see how to use it/ search it.


__________

Anyone else looking to generate the binlog file, I update the above pipeline with - 

```yaml
 arguments: -f:net8.0-ios -c:Release /p:ArchiveOnBuild=true /p:MtouchUseLlvm=$(OptimiseBuild) /bl:msbuild.binlog -verbosity:diagnostic
```
```yaml
  - task: CopyFiles@2
    displayName: Copy .binlog files
    inputs:
      Contents: '**/*.binlog'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true
```
