### ISSUE TITLE
[testing] Resizetizer unit tests failing on ARM

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#26516]
### Description

When we try to run the pipelines on ARM machines, one of our  Build stages of the handlers pipeline fails on the unit test step.
 

### Steps to Reproduce

Run the pipeline on arm agent change the build platform pool demands to 

```
- name: macOS
  poolName: $(macOSXVmPool)
  vmImage: $(macOSXVmImage)
  demands:
  - macOS.Name -equals Sonoma
  - macOS.Architecture -equals arm64
```

### Link to public reproduction project repository

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10687323&view=ms.vss-test-web.build-test-results-tab&runId=117781849&paneView=debug

### Affected platforms

macOS, iOS

### Relevant log output

```shell
Image was not equal. Error was 0.0030381944444444445% (21 pixels). See /Users/builder/azdo/_work/2/s/artifacts/bin/Resizetizer.UnitTests/Debug/net9.0/../../../../../src/SingleProject/Resizetizer/test/UnitTests/errors/imageresults/ResizetizeImagesTests+ExecuteForAndroid/SingleRasterAppIconWithOnlyPathSucceedsWithoutVectors/output-camera-folderSLASHthe_alias.png-m-r.mask.png
```
