### ISSUE TITLE
Platform-specific CSS styling

### ISSUE THREAD

**Issue by chucker** [dotnet/maui#5780]
### Description

Right now, `OnPlatform` can be used to provide platform-specific styling to a control:

```xml
    <ContentPage.BackgroundColor>
        <OnPlatform x:TypeArguments="Color">
            <On Platform="macOS">Transparent</On>
            <On Platform="iOS">White</On>
        </OnPlatform>
    </ContentPage.BackgroundColor>
```

However, no equivalent appears to exist for CSS, where a selector can apply to only a certain platform.

### Public API Changes

I propose the CSS-esque approach of creating a [pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:is) named `:on-platform()` for this.

The above would then work as follows in a stylesheet:

```css
^contentpage:on-platform(macOS) {
    background-color: transparent;
}

^contentpage:on-platform(iOS) {
    background-color: white;
}
```

### Intended Use-Case

This expands the viability of exclusively using CSS (rather than XAML) for styling.
