### ISSUE TITLE
Unable to install latest workloads in Azure Pipelines

### ISSUE THREAD

**Issue by RichardMarsh** [dotnet/maui#6983]
### Description

At first the below command (as part of a yaml pipeline file) worked fine to install and build MAUI apps in our pipeline

`dotnet.exe workload install maui-ios maui-android`

After RC1 rolled out the above command still worked, but no longer got the latest MAUI versions and has been stuck on the last preview version

![image](https://user-images.githubusercontent.com/54434905/167589379-7c440df1-fd16-4e0a-a83c-c77177d66261.png)

I then tried to force the version using the below command

`install maui-ios maui-android --from-rollback-file https://aka.ms/dotnet/maui/rc.2.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json`

which yielded the following

`Workload installation failed: Failed to install manifest microsoft.net.sdk.android version 32.0.300-rc.2.27: microsoft.net.sdk.android.manifest-6.0.200::32.0.300-rc.2.27 is not found in NuGet feeds `

See logs.

Because of this downgrade to preview 14 we can't build our projects which uses the latest rc versions.

### Steps to Reproduce

Using a hosted azure pipeline, create a MAUI build step that installs the workload. Example below
```
  - task: DotNetCoreCLI@2
         displayName: 'Install MAUI workloads'
         inputs:
           command: 'custom'
           custom: 'workload'
           arguments: 'install maui-ios maui-android --from-rollback-file https://aka.ms/dotnet/maui/rc.2.json --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json'
```

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 14

### Affected platforms

iOS, Android

### Affected platform versions

NA

### Relevant log output

```shell
Installing workload manifest microsoft.net.sdk.android version 32.0.300-rc.2.27…
Workload installation failed. Rolling back installed packs...
Installing workload manifest microsoft.net.sdk.android version 31.0.200-preview.13.41…
Installation rollback failed: Failed to install manifest microsoft.net.sdk.android version 31.0.200-preview.13.41: The transaction has aborted..
Workload installation failed: Failed to install manifest microsoft.net.sdk.android version 32.0.300-rc.2.27: microsoft.net.sdk.android.manifest-6.0.200::32.0.300-rc.2.27 is not found in NuGet feeds https://aka.ms/dotnet6/nuget/index.json;https://api.nuget.org/v3/index.json"..
```
